### PR TITLE
Right2drive/db 1/react init

### PR DESCRIPTION
**Pull request by Right2Drive**
A boilerplate using React. If this goes through, there are several tasks that should be opened up out of the scope of initial configuration

1) Project README
2) At some point we should look into why they keep two separate webpack files, and if there is not a good reason for doing so, use `webpack-merge` to reduce code duplication

### CODE REVIEW

**Comment by enochtsang** [comment]
So Vue wasn't happening?

**Comment by Right2Drive** [comment]
I wanted a backup in case I couldn't make Vue happen, we can choose between both, although I don't think we should make @mfalthaw review both (pretty sure that's abuse)

**Comment by mfalthaw** [comment]
lol I'm a bit confused, so I'm not reviewing this? @Right2Drive @enochtsang

**Comment by enochtsang** [comment]
@mfalthaw,  @Right2Drive has given us the option of both. I don't really know what his intent is in terms of which to review to complete this item.

**Comment by Right2Drive** [comment]
I think going ahead with the Vue one is in the best interests as far as performance and tooling are considered

**Comment by enochtsang** [comment]
Sounds good, closing this PR then.

**Pull request closed without merging**
